// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview An AI tool for curating trivia questions based on difficulty, topic coverage, and player engagement metrics.
 *
 * - curateTriviaQuestions - A function that curates trivia questions based on specified metrics.
 * - CurateTriviaQuestionsInput - The input type for the curateTriviaQuestions function.
 * - CurateTriviaQuestionsOutput - The return type for the curateTriviaQuestions function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const CurateTriviaQuestionsInputSchema = z.object({
  topic: z.string().describe('The main topic of the trivia questions.'),
  difficulty: z
    .enum(['easy', 'medium', 'hard'])
    .describe('The desired difficulty level of the questions.'),
  numberOfQuestions: z
    .number()
    .min(1)
    .max(20)
    .describe('The number of trivia questions to generate.'),
  playerEngagementMetrics: z
    .string()
    .optional()
    .describe(
      'Optional. Player engagement metrics or feedback to tailor questions.'
    ),
});
export type CurateTriviaQuestionsInput = z.infer<
  typeof CurateTriviaQuestionsInputSchema
>;

const CurateTriviaQuestionsOutputSchema = z.object({
  questions: z.array(
    z.object({
      question: z.string().describe('The trivia question.'),
      answer: z.string().describe('The correct answer to the question.'),
      difficulty: z
        .enum(['easy', 'medium', 'hard'])
        .describe('The difficulty level of the question.'),
      topic: z.string().describe('The topic of the question.'),
    })
  ).describe('An array of curated trivia questions.'),
});
export type CurateTriviaQuestionsOutput = z.infer<
  typeof CurateTriviaQuestionsOutputSchema
>;

export async function curateTriviaQuestions(
  input: CurateTriviaQuestionsInput
): Promise<CurateTriviaQuestionsOutput> {
  return curateTriviaQuestionsFlow(input);
}

const curateTriviaQuestionsPrompt = ai.definePrompt({
  name: 'curateTriviaQuestionsPrompt',
  input: {schema: CurateTriviaQuestionsInputSchema},
  output: {schema: CurateTriviaQuestionsOutputSchema},
  prompt: `You are an expert trivia question curator. Your task is to generate {{numberOfQuestions}} trivia questions based on the following criteria:

Topic: {{topic}}
Difficulty: {{difficulty}}

{{#if playerEngagementMetrics}}
Player Engagement Metrics: {{playerEngagementMetrics}}
Use these metrics to tailor the questions to maximize player engagement.
{{/if}}

Each question should be relevant to the topic, appropriate for the specified difficulty level, and engaging for players.  The output must be a valid JSON array of question objects.

Here's the schema for each question:
{
  question: string, // The trivia question.
  answer: string, // The correct answer to the question.
  difficulty: 'easy' | 'medium' | 'hard', // The difficulty level of the question.
  topic: string // The topic of the question.
}

Ensure the difficulty of each question matches the difficulty level specified.`,
});

const curateTriviaQuestionsFlow = ai.defineFlow(
  {
    name: 'curateTriviaQuestionsFlow',
    inputSchema: CurateTriviaQuestionsInputSchema,
    outputSchema: CurateTriviaQuestionsOutputSchema,
  },
  async input => {
    const {output} = await curateTriviaQuestionsPrompt(input);
    return output!;
  }
);
